config/routes.rb
CarmeBlanch::Application.routes.draw do
  root :to => "cuenta#index"
  resources :cuenta
  resources :var_confs
  resources :categoria
  resources :tipos
  resources :asientos 
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions

end

app/models/asiento.rb
class Asiento < ActiveRecord::Base
  validates :fecha, :tipo, :monto, :presence => true
  belongs_to :categorium
  belongs_to :tipo
  belongs_to :cuentum
  self.per_page = 10
  scope :cuentas, lambda {|cuentum_id| where "'asientos'.'cuentum_id' = ?", cuentum_id}
  scope :descen, order('fecha DESC, id DESC')
  scope :ascen, order('fecha ASC, id ASC')
  scope :sel_trozo,lambda {|fech1,fech2,categorium_id,cuentum_id,tipo_id| where("(date('asientos'.'fecha') >= ?) and 
                                              (date('asientos'.'fecha') <= ?) and 
                                              ('asientos'.'categorium_id' = ?) and
                                              ('asientos'.'cuentum_id' = ?) and
                                              ('asientos'.'tipo_id' = ?)",
                                               fech1,fech2,categorium_id,cuentum_id,tipo_id)}
  
  @mes_nom = {
              1 => "Enero",
              2 => "Febrero",
              3 => "Marzo",
              4 => "Abril",
              5 => "Mayo",
              6 => "Junio",
              7 => "Julio",
              8 => "Agosto",
              9 => "Septiembre",
              10 => "Octubre",
              11 => "Noviembre",
              12 => "Diciembre"
             }
                                              
  def self.informe_hasta_dia
    gap = Date.today
    salida = ["Informe del mes de #{@mes_nom[gap.month]} hasta el dia #{gap.day}"]
    cates = Categorium.all.map{|x| [x.id,x.descripcion]}
    cuentas = Cuentum.all.map{|x| [x.id,x.nombre]}
    tipos = Tipo.all.map{|x| [x.id,x.descripcion]} 
    n = 0

    cuentas.each do |cuenta|
          @suma_total = 0
      salida  << "<h2>Cuenta #{cuenta[1]}</h2>"  
      tipos.each do |tipo| 
        suma = 0
        salida  << "<h3>#{tipo[1]}</h3>"
        cates.each do |cate|
          item = cate[1].capitalize
          valor = self.sel_trozo(gap.at_beginning_of_month,gap,cate[0],cuenta[0],tipo[0]).sum(:monto)             
          if (valor != 0)
            suma += valor
            z = [item,valor]
            salida <<z
          end
        end
        item = "<b>Sub total #{tipo[1].downcase}</b>"
        z = [item,suma]
        if tipo[1]=='Ingreso'
          @suma_total += suma
        elsif tipo[1]=='Gasto'
          @suma_total -= suma
        end
        salida <<z
      end
      salida << ['<span class="green">Saldo mensual</span>',@suma_total]
    end
    salida
  end
end

app/controllers/asientos_controller.rb
class AsientosController < ApplicationController
  # GET /asientos
  # GET /asientos.json
  load_and_authorize_resource
  
  def index    
    if params[:asiento]
      @cuenta = params[:asiento][:cuentum_id] 
    elsif params[:cuentum_id]
      @cuenta = params[:cuentum_id]
    else
      @cuenta = 1
    end
    @asientos2 = Asiento.cuentas(@cuenta).ascen
    @asientos = Asiento.cuentas(@cuenta).descen.page(params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @asientos }
      format.csv
    end
  end

  # GET /asientos/1
  # GET /asientos/1.json
  def show
    @asiento = Asiento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @asiento }
    end
  end

  # GET /asientos/new
  # GET /asientos/new.json
  def new
    if params[:asiento]
      @cuenta = params[:asiento][:cuentum_id] 
    elsif params[:cuentum_id]
      @cuenta = params[:cuentum_id]
    else
      @cuenta = 1
    end 
    @asiento = Asiento.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @asiento }
    end
  end

  # GET /asientos/1/edit
  def edit
    if params[:asiento]
      @cuenta = params[:asiento][:cuentum_id] 
    elsif params[:cuentum_id]
      @cuenta = params[:cuentum_id]
    else
      @cuenta = 1
    end
    @asiento = Asiento.find(params[:id])
  end

  # POST /asientos
  # POST /asientos.json
  def create
    @asiento = Asiento.new(params[:asiento])

    respond_to do |format|
      if @asiento.save
        format.html { redirect_to @asiento, :notice => 'El apunte fue creado.' }
        format.json { render :json => @asiento, :status => :created, :location => @asiento }
      else
        format.html { render :action => "new" }
        format.json { render :json => @asiento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /asientos/1
  # PUT /asientos/1.json
  def update
    @asiento = Asiento.find(params[:id])

    respond_to do |format|
      if @asiento.update_attributes(params[:asiento])
        format.html { redirect_to @asiento, :notice => 'El apunte fue cambiado.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @asiento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /asientos/1
  # DELETE /asientos/1.json
  def destroy
    @asiento = Asiento.find(params[:id])
    @asiento.destroy

    respond_to do |format|
      format.html { redirect_to asientos_url }
      format.json { head :ok }
    end
  end
end

app/helpers/asientos_helper.rb
module AsientosHelper
  def estado_caja(asientos)
    @caja = 0
    @lista_caja = Hash.new
    asientos.each do |asiento|
      if asiento.tipo_id == 1 then
        @caja += asiento.monto.to_d
      elsif asiento.tipo_id == 2 then
        @caja -= asiento.monto.to_d
      end
      caja = @caja
      @lista_caja[asiento.id] = caja
    end
      salida_caja = [@caja, @lista_caja]
  end
   
end

app/views/asientos/_form.html.erb
<%= form_for @asiento do |f| %>
  
  <% if @asiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asiento.errors.count, "error") %> prohibited this asiento from being saved:</h2>

      <ul>
        <% @asiento.errors.full_messages.each do |msg| %>
          <li><%= msg %><//li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :cuentum_id, :value => @cuenta %>
  <b>Fecha:</b>
    <%= f.date_select(:fecha, :order => [:day,:month,:year]) %>
    <p><b><span><%= f.label :tipo %></span></b>
      <%= @tipos=Tipo.find(:all, :order=>"descripcion" )
         f.collection_select(:tipo_id, @tipos, :id, :descripcion, :include_blank => true) %> 
  <b>Categoría:</b>
	<%= @categoria=Categorium.find(:all,:order=>"descripcion")
	    f.collection_select(:categorium_id,@categoria,:id,:descripcion) %></p>
  		<p><b>Descripción:</b>
			<%= f.text_field :descripcion %></p>
		<p><b>Cantidad:</b>
			<%= f.text_field :monto %></p>
  <p><b>Observaciones:</b><br />
	<%= f.text_area :observaciones, :rows => 3 %></p>
  <p><%= f.submit "Guardar"%></p>
<% end %>
		<script>
		  $('#asiento_tipo_id').change(function(){			
		    if ($(this).children('option:selected').text() === 'Gasto') {
		      $('span').removeClass('ingreso').addClass('gasto');
		    } else if ($(this).children('option:selected').text() === 'Ingreso'){
		      $('span').removeClass('gasto').addClass('ingreso');
		    }  
		      else    {
		      $('span').removeClass('gasto').removeClass('ingreso');
		    }
		   });
		</script>

		
  

app/views/asientos/edit.html.erb
<h1>Modificando el apunte
<% cuentum = Cuentum.find(@cuenta) %>
<%= cuentum.nombre%>  de <%= cuentum.moneda%></h1>
<%= render 'form' %>

<%= link_to "Cambiar de cuenta", cuenta_path %>
<%= form_tag asientos_path, :method => "get" do  %>
  <%= hidden_field_tag :cuentum_id, cuentum.id %>
  <%= button_tag 'Ver cuenta' %>
<% end %>
<%= link_to 'Mostrar', @asiento %> |

app/views/asientos/index.csv.erb
<% estado = estado_caja(@asientos2) %>
<%- headers = ["Id", "Fecha","Tipo","Descripcion","Monto","Observaciones"] -%>
<%= FasterCSV.generate_line headers, options = {:row_sep => "\t", :quote_char => "'"} %>
<%- @asientos2.each do |n| -%>
<%- row = [ n.id, n.fecha,n.tipo.descripcion,n.descripcion,n.monto, estado[1][n.id]] -%>
<%= FasterCSV.generate_line row, options = {:row_sep => "\t", :quote_char => "'"}  %>
<%- end -%>

app/views/asientos/index.html.erb
<h1>Lista de apuntes contables</h1>

<h2>Cuenta <%= Cuentum.find(@cuenta).nombre %></h2>
<% estado = estado_caja(@asientos2)%>

<h2> Estado de  <%= Cuentum.find(@cuenta).nombre %>: 
  <% if estado[0] < 0 %>
    <span class="egreso">
      <%= estado[0] %>
    </span>
  <% elsif estado[0] > 0 %>
    <span class="ingreso">
      <%= estado[0] %>
    </span>
  <% else %>
  <% end %> 
  <%= Cuentum.find(@cuenta).moneda %>
</h2>

<span class="nuevo_item">
  <% if can? :create, Asiento %>
    <%= form_tag new_asiento_path, :method => 'get' do %>
	  <%= hidden_field_tag :cuentum_id, @cuenta %>
	  <%= button_tag 'Apunte nuevo' %>
    <% end %>
  <% end %>
</span>

<%= will_paginate_with_i18n @asientos %><br />

<table class="indice">

  <tr>
   <th>Fecha</th>
   <th>Tipo</th>
   <th>Categoria</th>
   <th>Descripcion</th>
   <th>Monto</th>
   <th>Evolución caja</th>
   <th></th>
   <th></th>
   <th></th>
  </tr>

  <% @asientos.each do |asiento| %>  
    <% if asiento.tipo_id == 2 then %>
      <tr class= "egreso <%= cycle('odd', 'even') -%>">
    <% elsif asiento.tipo_id == 1 %>
	  <tr class="ingreso <%= cycle('odd', 'even') -%>">
    <% else %>
	  <tr>
    <% end %>
  
      <td><%= asiento.fecha %></td>
      <td><%= asiento.tipo.descripcion %></td>
      <td><%= asiento.categorium.descripcion %></td>
      <td><%= asiento.descripcion %></td>
      <td class="num_align"> <%= asiento.monto %></td>
      <% if estado[1][asiento.id] >0  %>
        <td class="ingreso">
      <% elsif estado[1][asiento.id] <0 %>
	    <td class="egreso">
      <% else %>
	    <td class="num_align">
      <% end %>
	  <%= estado[1][asiento.id] %>
	  </td>
      <td><%= link_to 'Mostrar', asiento %></td>
      <% if can? :update, asiento %>
        <td>
          <%= form_tag edit_asiento_path(asiento) , :method => "get" do  %>
			<%= hidden_field_tag :cuentum_id, asiento.cuentum_id %>
			<%= button_tag 'Modificar apunte' %>
		  <% end %>
		</td>
      <% end %>
      <%  if can? :destroy, asiento %>
        <td><%= link_to 'Eliminar', asiento, :confirm => '¿Está usted seguro?', :method => :delete %></td>
      <% end %>
    </tr> 
  <% end %>

</table>

<br />
<span class="nuevo_item">
  <% if can? :create, Asiento %>
    <%= form_tag new_asiento_path, :method => 'get' do %>
	  <%= hidden_field_tag :cuentum_id, @cuenta %>
	  <%= button_tag 'Apunte nuevo' %>
    <% end %>	
  <% end %>
</span>
<%= link_to "Cambiar de cuenta", cuenta_path %>
<br />
<%= will_paginate_with_i18n @asientos %>
<br />
<%= link_to "Exportar a csv", request.parameters.merge({:format => :csv}) %>

app/views/asientos/new.html.erb
<div id="new">
  <h1>Apunte nuevo en la cuenta 
	<% cuentum = Cuentum.find(@cuenta) %>
	<%= cuentum.nombre%> de <%= cuentum.moneda%></h1>

  <%= render 'form' %>

  <%= link_to "Cambiar de cuenta", cuenta_path %>
  <%= form_tag asientos_path, :method => "get" do  %>
    <%= hidden_field_tag :cuentum_id, cuentum.id %>
    <%= button_tag 'Ver cuenta' %>
  <% end %>
</div>

app/views/asientos/show.html.erb
<p>  
	Cuenta de <%= @asiento.cuentum.nombre %> en <%= @asiento.cuentum.moneda %><br />
    <% if @asiento.tipo.descripcion =='Gasto' %>
      <span id="gasto">
	<% else %>
	  <span id="ingreso">
	<% end %>
    <b>Tipo:</b>
      <%= @asiento.tipo.descripcion %>
   </span></p>
  <p>
    <b>Fecha:</b>
    <%= @asiento.fecha %>
  </p>

<p>
  <b>Categoría:</b>
  <%= @asiento.categorium.descripcion %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @asiento.descripcion %>
</p>

<p>
  <b>Monto:</b>
  <%= @asiento.monto %>
</p>

<p>
  <b>Observaciones:</b>
  <%= @asiento.observaciones %>
</p>
<div id="show">
<% if can? :update, Asiento %>
  <%= form_tag edit_asiento_path(@asiento) , :method => "get" do  %>
    <%= hidden_field_tag :cuentum_id, @asiento.cuentum_id %>
    <%= button_tag 'Modificar apunte' %>
  <% end %>
<% end %>

<%= form_tag asientos_path, :method => "get" do  %>
  <%= hidden_field_tag :cuentum_id, @asiento.cuentum_id %>
  <%= button_tag 'Ver cuenta' %>
<% end %>

<% if can? :create, Asiento %>
    <%= form_tag new_asiento_path, :method => 'get' do %>
	  <%= hidden_field_tag :cuentum_id, @asiento.cuentum_id %>
	  <%= button_tag 'Apunte nuevo' %>	
    <% end %>
<% end %>

<%= link_to "Cambiar de cuenta", cuenta_path %>

</div>